### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by punkpeye** [amidabuddha/unichat-mcp-server#3]
I'm trying to start this server so I can mark the associated [listing](https://glama.ai/mcp/servers/8wecix16ff) as tested.

### Current Behavior

This is my `Dockerfile`:

```Dockerfile
FROM python:3.11

RUN pip install uv

WORKDIR /app

RUN git clone https://github.com/amidabuddha/unichat-mcp-server .



RUN uv sync

CMD ["uv", "run", "unichat-mcp-server"]
```

When I run it, I get the following error:

```
Invalid model specified: unichat-model-v1
Traceback (most recent call last):
  File "/app/.venv/bin/unichat-mcp-server", line 5, in <module>
    from unichat_mcp_server import main
  File "/app/src/unichat_mcp_server/__init__.py", line 1, in <module>
    from . import server
  File "/app/src/unichat_mcp_server/server.py", line 26, in <module>
    raise ValueError(f"Unsupported model: {MODEL}")
ValueError: Unsupported model: unichat-model-v1

```

### Expected Behavior

The server should start correctly when using `uv run`.

### Suggested Improvement

I believe the issue here is that unichat is trying to validate model name at start. Is there a way to delay this until tools are used?

Could you provide a complete example in the README showing how to start the server using `uv run`?

This would improve usability for developers and help automated systems like [Glama](https://glama.ai/mcp/servers) to test the server

**Comment by amidabuddha** [comment]
Hi, you just need to use a supported model, "unichat-model-v1" is not among them.

We support all popular up-to-date models, as we see no point to include older options that are usually more expensive and less efficient, it is unlikely someone to use them unless unaware of recent developments. 

For automation you may use something stable and popular as predefined such as "chatgpt-4o-latest" or "claude-3-5-haiku-latest" and add it to the env at runtime.

The list of supported models is dynamic but you may also fetch a model from the [unichat](https://github.com/amidabuddha/unichat/blob/main/unichat/models.py) repo like this:

```dockerfile
FROM python:3.11

RUN pip install uv

WORKDIR /app

RUN git clone https://github.com/amidabuddha/unichat-mcp-server .

RUN uv sync

# Install curl
RUN apt-get update && apt-get install -y curl

# Store the first OpenAI model in an environment variable
ENV UNICHAT_MODEL=$(curl -s https://raw.githubusercontent.com/amidabuddha/unichat/refs/heads/main/unichat/models.py | grep -A1 '"openai_models": \[' | tail -n1 | grep -o '"[^"]*"' | tr -d '"')

ENV UNICHAT_API_KEY="fake-test-key"

CMD ["uv", "run", "unichat-mcp-server"]
```

I am also sharing here the current list, for your reference, in case you decide to hardcode a model, instead of using `curl`:
```json
{
    "anthropic_models": [
        "claude-3-5-haiku-latest",
        "claude-3-5-sonnet-latest",
        "claude-3-opus-latest"
    ],
    "mistral_models": [
        "mistral-small-latest",
        "mistral-large-latest"
    ],
    "openai_models": [
        "chatgpt-4o-latest",
        "gpt-4o-mini",
        "gpt-4o",
        "gpt-4o-2024-11-20",
        "o1-mini",
        "o1-preview",
        "o1"
    ],
    "grok_models": [
        "grok-beta"
    ],
    "gemini_models": [
        "gemini-1.5-flash",
        "gemini-1.5-pro",
        "gemini-2.0-flash-exp",
        "gemini-2.0-flash-thinking-exp",
        "gemini-exp-1206"
    ]
}
```
